"""Classify files into roles (entry, route, test, config, ...) from path, name, and content."""

from __future__ import annotations

import posixpath
import re
from dataclasses import dataclass, field

from metis.model import Symbol
from metis.scan.walker import lang_label

PRIORITY = [
    "entry",
    "route",
    "test",
    "migration",
    "schema",
    "model",
    "ci",
    "config",
    "build",
    "script",
    "doc",
    "generated",
    "vendored",
]
LABEL = {
    "entry": "Entry point",
    "route": "HTTP routes",
    "test": "Test module",
    "migration": "Database migration",
    "schema": "Database schema",
    "model": "Data models",
    "ci": "CI workflow",
    "config": "Configuration",
    "build": "Build file",
    "script": "Script",
    "doc": "Documentation",
    "generated": "Generated file",
    "vendored": "Vendored code",
}
GENERATED_MARKERS = re.compile(
    r"do not edit|generated by|@generated|auto-?generated|automatically generated", re.I
)
GENERATED_NAMES = re.compile(
    r"(_pb2\.py|\.pb\.go|_pb\.(ts|js)|\.min\.(js|css)|\.generated\.|\.g\.(cs|dart))$"
)
LOCK_NAMES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "uv.lock",
    "Cargo.lock",
    "go.sum",
    "composer.lock",
    "Gemfile.lock",
    "Pipfile.lock",
}
VENDOR_DIRS = {"vendor", "third_party", "thirdparty", "node_modules", "extern", "external"}
TEST_DIRS = {"tests", "test", "__tests__", "spec", "specs", "testing"}
TEST_NAME = re.compile(
    r"(^|/)(test_[^/]+\.py|[^/]+_test\.(py|go|rb)|[^/]+\.(test|spec)\.(js|jsx|ts|tsx|mjs)|[^/]+Test\.(java|kt|cs|scala)|test[^/]*\.(sh|bash))$"
)
CI_PATHS = re.compile(
    r"(^|/)(\.github/workflows/|\.gitlab-ci\.yml|\.circleci/|Jenkinsfile|\.travis\.yml|azure-pipelines\.yml|bitbucket-pipelines\.yml|\.drone\.yml)"
)
MIGRATION = re.compile(r"(^|/)(migrations?|alembic/versions|db/migrate)/|migration", re.I)
BUILD_NAMES = {
    "Dockerfile",
    "Makefile",
    "CMakeLists.txt",
    "setup.py",
    "setup.cfg",
    "pyproject.toml",
    "package.json",
    "go.mod",
    "build.gradle",
    "build.gradle.kts",
    "pom.xml",
    "Cargo.toml",
    "Gemfile",
    "composer.json",
    "tsconfig.json",
    "webpack.config.js",
    "vite.config.ts",
    "vite.config.js",
    "Justfile",
    "Taskfile.yml",
}
CONFIG_EXT = {".toml", ".ini", ".cfg", ".yaml", ".yml", ".json", ".env", ".properties", ".conf"}
CONFIG_NAMES = re.compile(r"(^|/)(settings|config|configuration|conf)[^/]*\.(py|js|ts|go|rb)$")
ENTRY_PATTERNS = {
    "python": re.compile(
        r'if\s+__name__\s*==\s*["\']__main__["\']|\bapp\s*=\s*(FastAPI|Flask|Celery)\(|uvicorn\.run\(|@(click|app|cli)\.(command|group)\(|typer\.Typer\('
    ),
    "javascript": re.compile(r"\.listen\(|require\.main\s*===\s*module|^\s*#!"),
    "typescript": re.compile(r"\.listen\(|require\.main\s*===\s*module"),
    "go": re.compile(r"^package\s+main\b.*?^func\s+main\s*\(", re.S | re.M),
    "bash": re.compile(r"^#!", re.M),
    "rust": re.compile(r"^fn\s+main\s*\(", re.M),
    "java": re.compile(r"public\s+static\s+void\s+main\s*\("),
    "csharp": re.compile(r"static\s+(void|int|async\s+Task)\s+Main\s*\("),
}
ROUTE_PATTERNS = {
    "python": re.compile(
        r"@\w+(?:\.\w+)*\.(get|post|put|delete|patch|route|api_route|websocket)\(|urlpatterns\s*="
    ),
    "javascript": re.compile(
        r"\b(app|router|server|api)\.(get|post|put|delete|patch|all|use)\(\s*['\"`/]"
    ),
    "typescript": re.compile(
        r"\b(app|router|server|api)\.(get|post|put|delete|patch|all|use)\(\s*['\"`/]|@(Get|Post|Put|Delete|Patch|Controller)\("
    ),
    "go": re.compile(r"\.(GET|POST|PUT|DELETE|PATCH|HandleFunc|Handle)\(\s*\""),
    "ruby": re.compile(r"^\s*(get|post|put|delete|patch|resources)\s+['\":]", re.M),
    "php": re.compile(r"Route::(get|post|put|delete|patch)\("),
}
MODEL_PATTERNS = {
    "python": re.compile(
        r"class\s+\w+\((BaseModel|models\.Model|db\.Model|Base|DeclarativeBase|TypedDict)\)|@dataclass"
    ),
    "typescript": re.compile(r"^\s*export\s+(interface|type)\s+\w+", re.M),
    "go": re.compile(r"^type\s+\w+\s+struct\s*\{", re.M),
    "java": re.compile(r"@Entity\b|@Table\("),
    "csharp": re.compile(r"\[Table\(|: DbContext"),
}
TEST_IMPORTS = re.compile(
    r"^\s*(import\s+(pytest|unittest)|from\s+(pytest|unittest)|import\s+\"testing\"|describe\(|it\(|test\(|@Test\b|\[Test\]|\[Fact\])",
    re.M,
)
SCHEMA_SQL = re.compile(r"CREATE\s+(TABLE|VIEW|SCHEMA|TYPE)", re.I)


@dataclass
class RoleResult:
    roles: list[str] = field(default_factory=list)
    title_hint: str | None = None
    generated: bool = False
    vendored: bool = False


def classify(
    path: str, lang: str | None, text: str, symbols: list[Symbol], is_doc: bool
) -> RoleResult:
    roles: set[str] = set()
    name = posixpath.basename(path)
    parts = path.split("/")
    dirs = set(parts[:-1])
    head = "\n".join(text.splitlines()[:25])
    ext = posixpath.splitext(name)[1].lower()

    vendored = bool(dirs & VENDOR_DIRS)
    generated = (
        name in LOCK_NAMES
        or bool(GENERATED_NAMES.search(name))
        or bool(GENERATED_MARKERS.search(head))
    )
    if vendored:
        roles.add("vendored")
    if generated:
        roles.add("generated")
    if is_doc:
        roles.add("doc")
    if CI_PATHS.search(path):
        roles.add("ci")
    if (
        dirs & TEST_DIRS
        or TEST_NAME.search(path)
        or (lang and TEST_IMPORTS.search(text) and "test" in name.lower())
    ):
        roles.add("test")
    if MIGRATION.search(path) and (
        lang in ("python", "sql", "javascript", "typescript", "go", "ruby")
    ):
        roles.add("migration")
    if (
        lang == "sql"
        and SCHEMA_SQL.search(text)
        or name in ("schema.prisma",)
        or ext in (".proto", ".graphql")
    ):
        roles.add("schema")
    if name in BUILD_NAMES or name.lower().startswith("dockerfile") or ext in (".mk",):
        roles.add("build")
    elif (
        ext in CONFIG_EXT or name.startswith(".env") or CONFIG_NAMES.search(path)
    ) and "ci" not in roles:
        roles.add("config")
    if lang:
        if (p := ENTRY_PATTERNS.get(lang)) and p.search(text):
            roles.add("entry")
        if (p := ROUTE_PATTERNS.get(lang)) and p.search(text):
            roles.add("route")
        if (p := MODEL_PATTERNS.get(lang)) and len(p.findall(text)) >= 2:
            roles.add("model")
    if lang == "bash" or (parts[0] in ("scripts", "bin", "tools") and lang):
        roles.add("script")

    ordered = [r for r in PRIORITY if r in roles]
    return RoleResult(
        roles=ordered,
        title_hint=_title(ordered, path, lang),
        generated=generated,
        vendored=vendored,
    )


def _title(roles: list[str], path: str, lang: str | None) -> str | None:
    name = posixpath.basename(path)
    if ".github/workflows/" in path:
        return "CI workflow - GitHub Actions"
    if name == ".gitlab-ci.yml":
        return "CI pipeline - GitLab"
    if name.lower().startswith("dockerfile"):
        return "Container build - Docker"
    if name == "docker-compose.yml" or name == "docker-compose.yaml" or name == "compose.yaml":
        return "Service composition - Docker Compose"
    if name in ("Makefile", "Justfile"):
        return f"Build file - {name[:-4] if name.endswith('file') else name}"
    if name == "package.json":
        return "Package manifest - npm"
    if name == "pyproject.toml":
        return "Package manifest - Python"
    if name == "go.mod":
        return "Module manifest - Go"
    if name.startswith(".env"):
        return "Environment file - dotenv"
    if lang == "python" and name == "__init__.py":
        return "Package marker - Python"
    for role in roles:
        if role in ("doc", "vendored"):
            continue
        suffix = lang_label(lang) if lang else "file"
        if role == "test" and lang == "python":
            suffix = "pytest" if True else suffix
        return f"{LABEL[role]} - {suffix}"
    return None
