"""Summaries that need no model at all: package markers, re-exports, generated and vendored files."""

from __future__ import annotations

import posixpath
import re

from metis.model import AiConnection, AiFileSummary, FileEntry, LocalScan
from metis.scan.walker import lang_label

GEN_MARKER = re.compile(r"(generated by[^\n.]*|do not edit[^\n]*)", re.I)


def _only_imports(fe: FileEntry, text: str) -> bool:
    code = [
        ln
        for ln in text.splitlines()
        if ln.strip() and not ln.strip().startswith(("#", "//", '"""', "'''", "*", "/*"))
    ]
    if not code:
        return True
    return (
        all(
            re.match(
                r"^\s*(from\s+\S+\s+import|import\s+|export\s+(\*|\{)|__all__\s*=|module\.exports\s*=|\s*[\w,\s]+\)?\s*$|\))",
                ln,
            )
            for ln in code
        )
        and not fe.symbols
    )


def template_summary(fe: FileEntry, scan: LocalScan, text: str | None) -> AiFileSummary | None:
    name = posixpath.basename(fe.path)
    lang = lang_label(fe.language)
    uses = [
        AiConnection(target=i.resolved_to.id, direction="uses", why="re-exports it")
        for i in fe.imports
        if i.resolved_to and i.resolved_to.kind in ("file", "dir", "symbol")
    ]

    def make(
        title: str,
        purpose: str,
        connections: list[AiConnection] | None = None,
        notes: str | None = None,
    ) -> AiFileSummary:
        return AiFileSummary(
            path=fe.path,
            content_hash=fe.content_hash,
            title=title,
            purpose=purpose,
            connections=connections or [],
            notes=notes,
            model="template",
            source="template",
        )

    if fe.vendored:
        return make(
            fe.title_hint or f"Vendored code - {lang}",
            "Third-party code copied into the repository. Treat it as external: fixes belong upstream, "
            "and local edits are lost when it is updated.",
        )
    if fe.generated:
        marker = GEN_MARKER.search(text or "")
        why = f" ({marker.group(1).strip()})" if marker else ""
        return make(
            fe.title_hint or f"Generated file - {lang}",
            f"Produced by a tool{why}. Do not edit it by hand; change the source it is generated from and regenerate.",
            notes="Edits here are overwritten on the next generation.",
        )
    if fe.language == "python" and name == "__init__.py":
        pkg = posixpath.dirname(fe.path) or "."
        if not fe.symbols and (text is None or not text.strip() or _only_imports(fe, text)):
            if uses:
                names = sorted({n for i in fe.imports for n in i.names if n != "*"})
                shown = ", ".join(names[:8]) + (", ..." if len(names) > 8 else "")
                return make(
                    "Package re-exports - Python",
                    f"Marks `{pkg}` as a package and re-exports {shown or 'its submodules'} so they can be imported from `{pkg.replace('/', '.')}` directly.",
                    uses,
                )
            return make(
                "Package marker - Python",
                f"Marks `{pkg}` as a Python package. It has no code of its own.",
            )
    if (
        fe.language in ("javascript", "typescript")
        and name.startswith("index.")
        and text
        and _only_imports(fe, text)
        and uses
    ):
        return make(
            f"Module re-exports - {lang}",
            "Collects and re-exports the modules of this folder so callers can import from the folder.",
            uses,
        )
    if name.startswith(".env"):
        keys = [r.name for r in fe.references if r.kind == "env_define"]
        shown = ", ".join(keys[:10]) + (", ..." if len(keys) > 10 else "")
        return make(
            "Environment file - dotenv",
            f"Defines {len(keys)} environment variable{'s' if len(keys) != 1 else ''} read by the code: {shown}.",
            [AiConnection(target=f"env:{k}", direction="uses", why="sets it") for k in keys[:20]],
            notes="Values here are local configuration; keep secrets out of version control.",
        )
    return None
